---
email_address: 'tianrunhe@gmail.com'
topic_arn: 'arn:aws:sns:us-east-1:481497395090:mealpal-reservation'
meals:
  - meal_name: 'Beets By Evergreens'
    restaurant_name: 'Evergreens - Lenora & 6th'
  - meal_name: 'When Berry Met Salad'
    restaurant_name: 'Evergreens - Lenora & 6th'
  - meal_name: 'The Super Bowl'
    restaurant_name: 'Evergreens - Lenora & 6th'
  - meal_name: 'The Notorious B.B.Q.'
    restaurant_name: 'Evergreens - Lenora & 6th'
  - meal_name: 'Cobb Your Enthusiasm'
    restaurant_name: 'Evergreens - Lenora & 6th'
  - meal_name: 'Beets By Evergreens'
    restaurant_name: 'Evergreens - 6th & Olive'
  - meal_name: 'When Berry Met Salad'
    restaurant_name: 'Evergreens - 6th & Olive'
  - meal_name: 'The Super Bowl'
    restaurant_name: 'Evergreens - 6th & Olive'
  - meal_name: 'The Notorious B.B.Q.'
    restaurant_name: 'Evergreens - 6th & Olive'
  - meal_name: 'Cobb Your Enthusiasm'
    restaurant_name: 'Evergreens - 6th & Olive'
  - meal_name: 'Fleifleh W/ Lamb'
    restaurant_name: 'Mamnoon Street - 6th Ave.'
  - meal_name: 'Fleifleh W/ Chicken'
    restaurant_name: 'Mamnoon Street - 6th Ave.'
  - meal_name: 'Clam Chowder W/ French Fries'
    restaurant_name: 'Pike Place Chowder- Pacific Place'
  - meal_name: 'Seafood Bisque W/ Fries'
    restaurant_name: 'Pike Place Chowder- Pacific Place'
  - meal_name: 'Crispy Garlic Chicken'
    restaurant_name: 'Thai U Up - Stewart St.'
  - meal_name: 'Volcano Chicken'
    restaurant_name: 'Thai U Up - Stewart St.'
...
